language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "ableneo"
script:
  - export JAVA_HOME=$HOME/openjdk11
  - install-jdk.sh -f 11 --target $JAVA_HOME
  - sonar-scanner -Dsonar.java.binaries=target -Dsonar.projectKey=liferay-db-setup-core-2_x
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
