language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "ableneo"
script:
  - mvn sonar:sonar -Dsonar.projectKey=liferay-db-setup-core-2_x
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
