language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "ableneo"
    projectKey: "liferay-db-setup-core-2x"
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
