= Thank you for considering contribution!
:TOC:

== TL;DR

. find issue for the problem
. if not found create one
. work or wait :)

== How to build

We didn't publish binary yet so you'll need to build the jar yourself. Here are the steps to do it:

. Download sources.
. Install JDK 1.8
. Install Maven 3.6.3 or higher.
. Run: `mvn clean install`

=== Automated local build environment setup with nix

==== nix + nix-shell
Sets up required JDK and all other software required for building. Does not change any global OS settings. Building environment is local to the project e.g. you're using JDK11 by default.

Helps if you want to build the project without changing global system JDK/Maven settings.

. Install nix: https://nixos.org/guides/install-nix.html
. Run:
+
```bash
cd liferay-db-setup-core
nix-shell
mvn clean install
```

==== nix + direnv
Enters local development environment for the project every time you cd into the project directory.

. Install nix: https://nixos.org/guides/install-nix.html
. Install direnv_nix: https://github.com/nix-community/nix-direnv#with-nix-env
. Run:
+
```bash
cd liferay-db-setup-core
mvn clean install
```

== Detail

In case of missing feature or a bug. Before doing anything else, please check if there is an open issue for the problem you've spotted. If not, please create an issue. The issue will be used as a mean of tracking discussion/documentation about the problem even if you'll fix it yourself.

Please link the issue in commit messages, as an example here is a commit message that references issue #1:

`fix broken feature #1`

I recommend https://chris.beams.io/posts/git-commit/[the very good guide] on writing best commit messages.

== Code formatting

To ease merging pains please use prettier formatting included in maven project.

To check if your formatting is ok run:
```bash
mvn prettier:check
```

To reformat all the source run:
```bash
mvn prettier:write
```
