name: SonarCloud analysis

on:
  push:
    branches: [ master, 1.x ]
  pull_request_target:
    types: [labeled]
    branches: [ master ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to run with secrets')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
            java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Sonar Scan
        env:
            # Needed to get some information about the pull request, if any
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pcoverage
